# Generated by Django 5.1 on 2024-08-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_remove_order_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("P", "Pending"),
                    ("C", "Completed"),
                    ("W", "Waiting For Payment"),
                ],
                default="W",
                max_length=255,
            ),
        ),
    ]
