# Generated by Django 5.1 on 2024-08-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="wallet",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
