# Generated by Django 5.1 on 2024-09-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_wallet"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="receive_reports",
            field=models.BooleanField(default=False),
        ),
    ]
