# Generated by Django 5.1 on 2024-09-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_chatroom_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatroom",
            name="name",
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
